### ISSUE TITLE
freecad-0.18.3: mpi USE flag conflict from netcdf constraints on hdf5 

### ISSUE THREAD

**Issue by CaptainBloodz** [waebbl/waebbl-gentoo#158]
freecad installed here whith all USE flags enabled, but mpi which triggers:
``  (sci-libs/hdf5-1.10.5:0/1.10.5::gentoo, installed) pulled in by
    sci-libs/hdf5:0/1.10.5=[hl(+),-mpi,-szip,zlib] required by (sci-libs/netcdf-4.6.1-r1:0/13::gentoo, installed)
                                  ^^^^                                                                                                               
    sci-libs/hdf5:0=[hl(+),mpi=,szip=,zlib] required by (sci-libs/netcdf-4.6.1-r1:0/13::gentoo, installed)``
I have no idea how 2 fix.

**Comment by waebbl** [comment]
Hi @CaptainBloodz, switching between `mpi` on and off isn't  easily done, mostly due to the way `sci-libs/hdf5` handles the `mpi` USE flag. The package even has a postinst warning when you switch the USE flag with it, telling, to uninstall it before switching the flag.

If you haven't already, you might want to try, whether using `--deep` together with either `--changed-use` or `--newuse` does the resolving correct. You basically have to install any dependency of freecad and also some of the reverse dependencies of these freecad deps with `mpi` enabled. From the error message, this specifically means installing `sci-libs/hdf5` and `sci-libs/netcdf` with `USE=mpi`. There might be more packages affected by this.
If this doesn't help, you can try to uninstall `sci-libs/hdf5` using `emerge -Ca` and then reinstall it with `USE=mpi`, which should trigger the re-emerging of dependant packages.

Feel free to ping me again, if these tips don't work.

**Comment by waebbl** [comment]
mpi USE flag has been gone from the ebuild, so there should be no further issues with this.
