### ISSUE TITLE
change in layout.conf?

### ISSUE THREAD

**Issue by CaptainBloodz** [waebbl/waebbl-gentoo#160]
Unavailable repository 'raiagent' referenced by masters entry in '/var/db/repos/waebbl/metadata/layout.conf'
What are we supposed to do? import this 'raiagent' as new repository?

Thks 4 ur attention.

**Comment by waebbl** [comment]
Yes you can use layman or eselect repository to enable it. It's temporary
and provides alternative ebuilds for shiboken and pyside, which you don't
have to use btw. Freecad works with both ebuilds. It's due to preparation
of bringing freecad back into the main tree.

Am Di., 24. Dez. 2019 um 22:23 Uhr schrieb CaptainBloodz <
notifications@github.com>:

**Comment by waebbl** [comment]
Closing. ::raiagent is no longer needed by my overlay.
