### ISSUE TITLE
Dependency missing (sci-libs/spooles)

### ISSUE THREAD

**Issue by rjhwelsh** [waebbl/waebbl-gentoo#246]
**Problem**
_sci-libs/spooles_ a dependency for the _sci-libs/calculix-ccx_ ebuild is missing in the upstream gentoo repository.

Seems like there was a cull of unstable sci-libs packages in February.
I'm not sure exactly what the reason for this was.

**Workaround**
Fetching the ebuild and popping it into my localrepo, _calculix-ccx_ builds fine. 

**Last available ebuild (before lastrites)**
https://github.com/gentoo/gentoo/tree/765fd34f5b58a9b9bf31b5002515314e5aee2879/sci-libs/spooles

**Additional context**
https://bugs.gentoo.org/568364 

**Closing remarks**
Just a heads up for anyone with the same issue.
Might want to consider adopting _spooles_ into this repo, I can submit a PR if you would like. 
(It's basically just copy-pasta)

Also your repo is pretty cool, thanks.

**Comment by khumarahn** [comment]
I have the same problem. I used the old ebuild for spooles, and it worked. I guess it would be good to restore spooles, at least in this repo (if not in the main tree).

**Comment by khumarahn** [comment]
Maybe freecad should have a use flag `fem` which would require calculix-ccx and gmsh?

**Comment by waebbl** [comment]
Thanks for bringing this up. I haven't noticed the removal back in february, haven't build the package for some time.

Good idea to bring it back into this repo. If you have the time, you're welcome to submit a PR, but if you do, please update to EAPI=7, my repo needs at least EAPI=6. This might involve some additional adjustments beside simple copy'n'paste. I can take care of it as well, although I'm quite busy currently and it can take some time.


> Maybe freecad should have a use flag `fem` which would require calculix-ccx and gmsh?

Freecad already has a `fem` USE flag which adds support for many different FEM solutions. There's no need for an additional USE flag, because freecad support a lot of packages out of the box, including calculix-cxx and gmsh. You only need to install them and freecad recognizes them upon startup. For a list of such packages see https://forum.freecadweb.org/viewtopic.php?f=42&t=37806. The correct way would be to add a info to `pkg_postinst` to point the user to this forum page or listing the packages in the message.

**Comment by khumarahn** [comment]
I added a PR for spooles.

I did not notice that fem use flag exists :-) It would be convenient if the freecad ebuild installed all needed packages so that everything just worked, but I see that this is quite complicated.

**Comment by waebbl** [comment]
Merged. Closing this issue.
