### ISSUE TITLE
media-gfx/freecad-9999: ${P}-0001-Gentoo-specific-disable-building-assembly-workbench.patch does not apply

### ISSUE THREAD

**Issue by fordfrog** [waebbl/waebbl-gentoo#255]
i just commented out the patch to get freecad-9999 emerged and all went fine. not sure whether it should be updated or dropped, afaics 0.18.4-r1 does not patch assembly workbench out.

**Comment by khumarahn** [comment]
same here

**Comment by RayOfLight1** [comment]
https://github.com/FreeCAD/FreeCAD/commit/f4ff61c3542285d52a4bccf7a2b25d8b85fc5358#diff-681ee8d7307ebdad79cf0c1a23a97051b532d22601d0da0cd6c49d499815381f

Is the source of our problems.

**Comment by waebbl** [comment]
@RayOfLight1 is right, I didn't notice that the option has been set to default OFF, that's why the patch fails.
@fordfrog Thanks for reporting. The reason why assembly has been patched out, is that it's not working and upstream won't patch the option out because it serves as a placeholder for when it's getting updated, see https://forum.freecadweb.org/viewtopic.php?f=4&t=39716 for reference.

I changed it and are currently building. There will be an update later this day.

**Comment by fordfrog** [comment]
@waebbl thanks :-)
